In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import json

In [2]:
#Opening watch history JSON
with open(r"C:\Users\0106o\OneDrive\Pictures\Documents\Datasets\Youtube Project Files\history\watch-history.json", encoding="utf-8") as f:
    data = json.load(f)

df = pd.json_normalize(data)
df

,header,title,titleUrl,subtitles,time,products,activityControls,description,details
0,YouTube,Watched Kubbi and Chumpatrol1 / Restoration of...,https://www.youtube.com/watch?v=cNz8GIDLn2A,"[{'name': 'Chumpatrol1', 'url': 'https://www.y...",2026-07-21T13:04:17.545Z,[YouTube],[YouTube watch history],NaN,NaN
1,YouTube,"Watched Shortened: Machine Learning, Modeling,...",https://www.youtube.com/watch?v=jUAm6d44Tl8,NaN,2026-07-21T13:04:10.712Z,[YouTube],"[Web & App Activity, YouTube watch history, Yo...",Watched at 9:04 AM,[{'name': 'From Google Ads'}]
2,YouTube,Watched Kubbi - Pathfinder (Official Music Video),https://www.youtube.com/watch?v=EwNsnPfnIoU,"[{'name': 'Kubbi', 'url': 'https://www.youtube...",2026-07-21T13:03:54.932Z,[YouTube],[YouTube watch history],NaN,NaN
3,YouTube,Watched Kubbi / Cascade,https://www.youtube.com/watch?v=B4ZjUoEKiLs,"[{'name': 'Kubbi', 'url': 'https://www.youtube...",2026-07-21T13:03:50.258Z,[YouTube],[YouTube watch history],NaN,NaN
4,YouTube,Watched Kubbi / Pathfinder,https://www.youtube.com/watch?v=KRm2zCqwd1c,"[{'name': 'Kubbi', 'url': 'https://www.youtube...",2026-07-21T13:03:31.732Z,[YouTube],[YouTube watch history],NaN,NaN
...,...,...,...,...,...,...,...,...,...
42195,YouTube,Watched Undertale - Mettaton NEO v2.0 (Fan-made),https://www.youtube.com/watch?v=0CteVubVnx8,"[{'name': 'A Huge Pancake', 'url': 'https://ww...",2025-02-17T00:40:56.630Z,[YouTube],[YouTube watch history],NaN,NaN
42196,YouTube,"Watched Undertale: Power of ""NEO"" (IKARUS Remix)",https://www.youtube.com/watch?v=uI0CxTgpA6Q,"[{'name': 'BlastProcessed', 'url': 'https://ww...",2025-02-17T00:38:41.966Z,[YouTube],[YouTube watch history],NaN,NaN
42197,YouTube,Watched TREMFYA 'Healing Is Possible' UC Nonsk...,https://www.youtube.com/watch?v=IK7QJ-XAL88,NaN,2025-02-17T00:38:30.401Z,[YouTube],"[Web & App Activity, YouTube watch history, Yo...",Watched at 7:38 PM,[{'name': 'From Google Ads'}]
42198,YouTube,Watched Dançe Do Sonic (Baile Funk) [@fazomade...,https://www.youtube.com/watch?v=g-BWnNahE1I,"[{'name': 'fazomadeabanger*', 'url': 'https://...",2025-02-17T00:36:29.163Z,[YouTube],[YouTube watch history],NaN,NaN
42199,YouTube,Watched 𝘿𝙖𝙣ç𝙖 𝘿𝙤 𝙎𝙤𝙣𝙞𝙘 - 𝙛𝙖𝙯𝙤𝙗𝙚𝙖𝙩𝙨 (𝙨𝙡𝙤𝙬𝙚𝙙 𝙩𝙤 ...,https://www.youtube.com/watch?v=eD_uEg-Kwe0,"[{'name': '𝙀𝙜𝙤𝙞𝙨𝙪𝙩𝙤 | エゴイスト', 'url': 'https://...",2025-02-17T00:35:44.802Z,[YouTube],[YouTube watch history],NaN,NaN

In [3]:
#Checking the dimensions of the dataset
df.shape

(42200, 9)

In [4]:
#Checking the types and names of each column
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 42200 entries, 0 to 42199
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   header            42200 non-null  str
 1   title             42200 non-null  str
 2   titleUrl          41838 non-null  str
 3   subtitles         26845 non-null  object
 4   time              42200 non-null  str
 5   products          42200 non-null  object
 6   activityControls  42200 non-null  object
 7   description       8628 non-null   str
 8   details           13181 non-null  object
dtypes: object(4), str(5)
memory usage: 2.9+ MB

In [5]:
#Checking which columns have the most nulls to determine which are worth keeping and which are being dropped
df.isnull().sum()

header                  0
title                   0
titleUrl              362
subtitles           15355
time                    0
products                0
activityControls        0
description         33572
details             29019
dtype: int64

In [6]:
#Dropping duplicates and checking if counts changed

df = df.drop_duplicates(subset = ['title', 'time'])
df.count()

header              42188
title               42188
titleUrl            41826
subtitles           26833
time                42188
products            42188
activityControls    42188
description          8628
details             13181
dtype: int64

In [7]:
#Creating a new source column to drop all videos that were forced ads from youtube
df["source"] = df["details"].apply(lambda x: x[0]["name"] if isinstance(x, list) and len(x) > 0 else None)
df

,header,title,titleUrl,subtitles,time,products,activityControls,description,details,source
0,YouTube,Watched Kubbi and Chumpatrol1 / Restoration of...,https://www.youtube.com/watch?v=cNz8GIDLn2A,"[{'name': 'Chumpatrol1', 'url': 'https://www.y...",2026-07-21T13:04:17.545Z,[YouTube],[YouTube watch history],NaN,NaN,NaN
1,YouTube,"Watched Shortened: Machine Learning, Modeling,...",https://www.youtube.com/watch?v=jUAm6d44Tl8,NaN,2026-07-21T13:04:10.712Z,[YouTube],"[Web & App Activity, YouTube watch history, Yo...",Watched at 9:04 AM,[{'name': 'From Google Ads'}],From Google Ads
2,YouTube,Watched Kubbi - Pathfinder (Official Music Video),https://www.youtube.com/watch?v=EwNsnPfnIoU,"[{'name': 'Kubbi', 'url': 'https://www.youtube...",2026-07-21T13:03:54.932Z,[YouTube],[YouTube watch history],NaN,NaN,NaN
3,YouTube,Watched Kubbi / Cascade,https://www.youtube.com/watch?v=B4ZjUoEKiLs,"[{'name': 'Kubbi', 'url': 'https://www.youtube...",2026-07-21T13:03:50.258Z,[YouTube],[YouTube watch history],NaN,NaN,NaN
4,YouTube,Watched Kubbi / Pathfinder,https://www.youtube.com/watch?v=KRm2zCqwd1c,"[{'name': 'Kubbi', 'url': 'https://www.youtube...",2026-07-21T13:03:31.732Z,[YouTube],[YouTube watch history],NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
42195,YouTube,Watched Undertale - Mettaton NEO v2.0 (Fan-made),https://www.youtube.com/watch?v=0CteVubVnx8,"[{'name': 'A Huge Pancake', 'url': 'https://ww...",2025-02-17T00:40:56.630Z,[YouTube],[YouTube watch history],NaN,NaN,NaN
42196,YouTube,"Watched Undertale: Power of ""NEO"" (IKARUS Remix)",https://www.youtube.com/watch?v=uI0CxTgpA6Q,"[{'name': 'BlastProcessed', 'url': 'https://ww...",2025-02-17T00:38:41.966Z,[YouTube],[YouTube watch history],NaN,NaN,NaN
42197,YouTube,Watched TREMFYA 'Healing Is Possible' UC Nonsk...,https://www.youtube.com/watch?v=IK7QJ-XAL88,NaN,2025-02-17T00:38:30.401Z,[YouTube],"[Web & App Activity, YouTube watch history, Yo...",Watched at 7:38 PM,[{'name': 'From Google Ads'}],From Google Ads
42198,YouTube,Watched Dançe Do Sonic (Baile Funk) [@fazomade...,https://www.youtube.com/watch?v=g-BWnNahE1I,"[{'name': 'fazomadeabanger*', 'url': 'https://...",2025-02-17T00:36:29.163Z,[YouTube],[YouTube watch history],NaN,NaN,NaN
42199,YouTube,Watched 𝘿𝙖𝙣ç𝙖 𝘿𝙤 𝙎𝙤𝙣𝙞𝙘 - 𝙛𝙖𝙯𝙤𝙗𝙚𝙖𝙩𝙨 (𝙨𝙡𝙤𝙬𝙚𝙙 𝙩𝙤 ...,https://www.youtube.com/watch?v=eD_uEg-Kwe0,"[{'name': '𝙀𝙜𝙤𝙞𝙨𝙪𝙩𝙤 | エゴイスト', 'url': 'https://...",2025-02-17T00:35:44.802Z,[YouTube],[YouTube watch history],NaN,NaN,NaN

In [8]:
#Filtering out ads from dataset
df = df[df['source'] != 'From Google Ads']
df

,header,title,titleUrl,subtitles,time,products,activityControls,description,details,source
0,YouTube,Watched Kubbi and Chumpatrol1 / Restoration of...,https://www.youtube.com/watch?v=cNz8GIDLn2A,"[{'name': 'Chumpatrol1', 'url': 'https://www.y...",2026-07-21T13:04:17.545Z,[YouTube],[YouTube watch history],NaN,NaN,NaN
2,YouTube,Watched Kubbi - Pathfinder (Official Music Video),https://www.youtube.com/watch?v=EwNsnPfnIoU,"[{'name': 'Kubbi', 'url': 'https://www.youtube...",2026-07-21T13:03:54.932Z,[YouTube],[YouTube watch history],NaN,NaN,NaN
3,YouTube,Watched Kubbi / Cascade,https://www.youtube.com/watch?v=B4ZjUoEKiLs,"[{'name': 'Kubbi', 'url': 'https://www.youtube...",2026-07-21T13:03:50.258Z,[YouTube],[YouTube watch history],NaN,NaN,NaN
4,YouTube,Watched Kubbi / Pathfinder,https://www.youtube.com/watch?v=KRm2zCqwd1c,"[{'name': 'Kubbi', 'url': 'https://www.youtube...",2026-07-21T13:03:31.732Z,[YouTube],[YouTube watch history],NaN,NaN,NaN
5,YouTube,"Watched ループザルーム feat. 初音ミク / ""Looping the Room...",https://www.youtube.com/watch?v=icBDYkfxpMs,"[{'name': 'ルシノ / rusino', 'url': 'https://www....",2026-07-21T12:47:14.153Z,[YouTube],[YouTube watch history],NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
42194,YouTube,Watched POWER OF [[NEO]] (BIG SHOT) :: Deltaru...,https://www.youtube.com/watch?v=mSppviwSUko,"[{'name': 'Geshtro', 'url': 'https://www.youtu...",2025-02-17T00:48:13.926Z,[YouTube],[YouTube watch history],NaN,NaN,NaN
42195,YouTube,Watched Undertale - Mettaton NEO v2.0 (Fan-made),https://www.youtube.com/watch?v=0CteVubVnx8,"[{'name': 'A Huge Pancake', 'url': 'https://ww...",2025-02-17T00:40:56.630Z,[YouTube],[YouTube watch history],NaN,NaN,NaN
42196,YouTube,"Watched Undertale: Power of ""NEO"" (IKARUS Remix)",https://www.youtube.com/watch?v=uI0CxTgpA6Q,"[{'name': 'BlastProcessed', 'url': 'https://ww...",2025-02-17T00:38:41.966Z,[YouTube],[YouTube watch history],NaN,NaN,NaN
42198,YouTube,Watched Dançe Do Sonic (Baile Funk) [@fazomade...,https://www.youtube.com/watch?v=g-BWnNahE1I,"[{'name': 'fazomadeabanger*', 'url': 'https://...",2025-02-17T00:36:29.163Z,[YouTube],[YouTube watch history],NaN,NaN,NaN
42199,YouTube,Watched 𝘿𝙖𝙣ç𝙖 𝘿𝙤 𝙎𝙤𝙣𝙞𝙘 - 𝙛𝙖𝙯𝙤𝙗𝙚𝙖𝙩𝙨 (𝙨𝙡𝙤𝙬𝙚𝙙 𝙩𝙤 ...,https://www.youtube.com/watch?v=eD_uEg-Kwe0,"[{'name': '𝙀𝙜𝙤𝙞𝙨𝙪𝙩𝙤 | エゴイスト', 'url': 'https://...",2025-02-17T00:35:44.802Z,[YouTube],[YouTube watch history],NaN,NaN,NaN

In [9]:
# df = df.drop(columns = ['products', 'activityControls', 'details', 'source', 'subtitles']
#Filtering out the channel names from the subtitles column
df['channelName'] = df['subtitles'].apply(lambda x: x[0]['name'] if isinstance(x, list) and len(x)> 0 else None)
df

,header,title,titleUrl,subtitles,time,products,activityControls,description,details,source,channelName
0,YouTube,Watched Kubbi and Chumpatrol1 / Restoration of...,https://www.youtube.com/watch?v=cNz8GIDLn2A,"[{'name': 'Chumpatrol1', 'url': 'https://www.y...",2026-07-21T13:04:17.545Z,[YouTube],[YouTube watch history],NaN,NaN,NaN,Chumpatrol1
2,YouTube,Watched Kubbi - Pathfinder (Official Music Video),https://www.youtube.com/watch?v=EwNsnPfnIoU,"[{'name': 'Kubbi', 'url': 'https://www.youtube...",2026-07-21T13:03:54.932Z,[YouTube],[YouTube watch history],NaN,NaN,NaN,Kubbi
3,YouTube,Watched Kubbi / Cascade,https://www.youtube.com/watch?v=B4ZjUoEKiLs,"[{'name': 'Kubbi', 'url': 'https://www.youtube...",2026-07-21T13:03:50.258Z,[YouTube],[YouTube watch history],NaN,NaN,NaN,Kubbi
4,YouTube,Watched Kubbi / Pathfinder,https://www.youtube.com/watch?v=KRm2zCqwd1c,"[{'name': 'Kubbi', 'url': 'https://www.youtube...",2026-07-21T13:03:31.732Z,[YouTube],[YouTube watch history],NaN,NaN,NaN,Kubbi
5,YouTube,"Watched ループザルーム feat. 初音ミク / ""Looping the Room...",https://www.youtube.com/watch?v=icBDYkfxpMs,"[{'name': 'ルシノ / rusino', 'url': 'https://www....",2026-07-21T12:47:14.153Z,[YouTube],[YouTube watch history],NaN,NaN,NaN,ルシノ / rusino
...,...,...,...,...,...,...,...,...,...,...,...
42194,YouTube,Watched POWER OF [[NEO]] (BIG SHOT) :: Deltaru...,https://www.youtube.com/watch?v=mSppviwSUko,"[{'name': 'Geshtro', 'url': 'https://www.youtu...",2025-02-17T00:48:13.926Z,[YouTube],[YouTube watch history],NaN,NaN,NaN,Geshtro
42195,YouTube,Watched Undertale - Mettaton NEO v2.0 (Fan-made),https://www.youtube.com/watch?v=0CteVubVnx8,"[{'name': 'A Huge Pancake', 'url': 'https://ww...",2025-02-17T00:40:56.630Z,[YouTube],[YouTube watch history],NaN,NaN,NaN,A Huge Pancake
42196,YouTube,"Watched Undertale: Power of ""NEO"" (IKARUS Remix)",https://www.youtube.com/watch?v=uI0CxTgpA6Q,"[{'name': 'BlastProcessed', 'url': 'https://ww...",2025-02-17T00:38:41.966Z,[YouTube],[YouTube watch history],NaN,NaN,NaN,BlastProcessed
42198,YouTube,Watched Dançe Do Sonic (Baile Funk) [@fazomade...,https://www.youtube.com/watch?v=g-BWnNahE1I,"[{'name': 'fazomadeabanger*', 'url': 'https://...",2025-02-17T00:36:29.163Z,[YouTube],[YouTube watch history],NaN,NaN,NaN,fazomadeabanger*
42199,YouTube,Watched 𝘿𝙖𝙣ç𝙖 𝘿𝙤 𝙎𝙤𝙣𝙞𝙘 - 𝙛𝙖𝙯𝙤𝙗𝙚𝙖𝙩𝙨 (𝙨𝙡𝙤𝙬𝙚𝙙 𝙩𝙤 ...,https://www.youtube.com/watch?v=eD_uEg-Kwe0,"[{'name': '𝙀𝙜𝙤𝙞𝙨𝙪𝙩𝙤 | エゴイスト', 'url': 'https://...",2025-02-17T00:35:44.802Z,[YouTube],[YouTube watch history],NaN,NaN,NaN,𝙀𝙜𝙤𝙞𝙨𝙪𝙩𝙤 | エゴイスト

In [10]:
#Checking if there are any other prefixes other than watched in the title column by getting the first word in each entry
df['title'].str.split(" ", n = 1).str[0].value_counts()

title
Watched    26200
Viewed      2725
Used          73
Visited        9
Name: count, dtype: int64

In [11]:
#Filtering out any records that were not watched videos

df = df[df['title'].str.startswith('Watched ')]
df

,header,title,titleUrl,subtitles,time,products,activityControls,description,details,source,channelName
0,YouTube,Watched Kubbi and Chumpatrol1 / Restoration of...,https://www.youtube.com/watch?v=cNz8GIDLn2A,"[{'name': 'Chumpatrol1', 'url': 'https://www.y...",2026-07-21T13:04:17.545Z,[YouTube],[YouTube watch history],NaN,NaN,NaN,Chumpatrol1
2,YouTube,Watched Kubbi - Pathfinder (Official Music Video),https://www.youtube.com/watch?v=EwNsnPfnIoU,"[{'name': 'Kubbi', 'url': 'https://www.youtube...",2026-07-21T13:03:54.932Z,[YouTube],[YouTube watch history],NaN,NaN,NaN,Kubbi
3,YouTube,Watched Kubbi / Cascade,https://www.youtube.com/watch?v=B4ZjUoEKiLs,"[{'name': 'Kubbi', 'url': 'https://www.youtube...",2026-07-21T13:03:50.258Z,[YouTube],[YouTube watch history],NaN,NaN,NaN,Kubbi
4,YouTube,Watched Kubbi / Pathfinder,https://www.youtube.com/watch?v=KRm2zCqwd1c,"[{'name': 'Kubbi', 'url': 'https://www.youtube...",2026-07-21T13:03:31.732Z,[YouTube],[YouTube watch history],NaN,NaN,NaN,Kubbi
5,YouTube,"Watched ループザルーム feat. 初音ミク / ""Looping the Room...",https://www.youtube.com/watch?v=icBDYkfxpMs,"[{'name': 'ルシノ / rusino', 'url': 'https://www....",2026-07-21T12:47:14.153Z,[YouTube],[YouTube watch history],NaN,NaN,NaN,ルシノ / rusino
...,...,...,...,...,...,...,...,...,...,...,...
42194,YouTube,Watched POWER OF [[NEO]] (BIG SHOT) :: Deltaru...,https://www.youtube.com/watch?v=mSppviwSUko,"[{'name': 'Geshtro', 'url': 'https://www.youtu...",2025-02-17T00:48:13.926Z,[YouTube],[YouTube watch history],NaN,NaN,NaN,Geshtro
42195,YouTube,Watched Undertale - Mettaton NEO v2.0 (Fan-made),https://www.youtube.com/watch?v=0CteVubVnx8,"[{'name': 'A Huge Pancake', 'url': 'https://ww...",2025-02-17T00:40:56.630Z,[YouTube],[YouTube watch history],NaN,NaN,NaN,A Huge Pancake
42196,YouTube,"Watched Undertale: Power of ""NEO"" (IKARUS Remix)",https://www.youtube.com/watch?v=uI0CxTgpA6Q,"[{'name': 'BlastProcessed', 'url': 'https://ww...",2025-02-17T00:38:41.966Z,[YouTube],[YouTube watch history],NaN,NaN,NaN,BlastProcessed
42198,YouTube,Watched Dançe Do Sonic (Baile Funk) [@fazomade...,https://www.youtube.com/watch?v=g-BWnNahE1I,"[{'name': 'fazomadeabanger*', 'url': 'https://...",2025-02-17T00:36:29.163Z,[YouTube],[YouTube watch history],NaN,NaN,NaN,fazomadeabanger*
42199,YouTube,Watched 𝘿𝙖𝙣ç𝙖 𝘿𝙤 𝙎𝙤𝙣𝙞𝙘 - 𝙛𝙖𝙯𝙤𝙗𝙚𝙖𝙩𝙨 (𝙨𝙡𝙤𝙬𝙚𝙙 𝙩𝙤 ...,https://www.youtube.com/watch?v=eD_uEg-Kwe0,"[{'name': '𝙀𝙜𝙤𝙞𝙨𝙪𝙩𝙤 | エゴイスト', 'url': 'https://...",2025-02-17T00:35:44.802Z,[YouTube],[YouTube watch history],NaN,NaN,NaN,𝙀𝙜𝙤𝙞𝙨𝙪𝙩𝙤 | エゴイスト

In [12]:
#Removing the Watched prefix to have only video titles in the column
df['title'] = df['title'].str.replace('^Watched ', '', regex = True)
df

,header,title,titleUrl,subtitles,time,products,activityControls,description,details,source,channelName
0,YouTube,Kubbi and Chumpatrol1 / Restoration of the Cairn,https://www.youtube.com/watch?v=cNz8GIDLn2A,"[{'name': 'Chumpatrol1', 'url': 'https://www.y...",2026-07-21T13:04:17.545Z,[YouTube],[YouTube watch history],NaN,NaN,NaN,Chumpatrol1
2,YouTube,Kubbi - Pathfinder (Official Music Video),https://www.youtube.com/watch?v=EwNsnPfnIoU,"[{'name': 'Kubbi', 'url': 'https://www.youtube...",2026-07-21T13:03:54.932Z,[YouTube],[YouTube watch history],NaN,NaN,NaN,Kubbi
3,YouTube,Kubbi / Cascade,https://www.youtube.com/watch?v=B4ZjUoEKiLs,"[{'name': 'Kubbi', 'url': 'https://www.youtube...",2026-07-21T13:03:50.258Z,[YouTube],[YouTube watch history],NaN,NaN,NaN,Kubbi
4,YouTube,Kubbi / Pathfinder,https://www.youtube.com/watch?v=KRm2zCqwd1c,"[{'name': 'Kubbi', 'url': 'https://www.youtube...",2026-07-21T13:03:31.732Z,[YouTube],[YouTube watch history],NaN,NaN,NaN,Kubbi
5,YouTube,"ループザルーム feat. 初音ミク / ""Looping the Rooms"" ft. H...",https://www.youtube.com/watch?v=icBDYkfxpMs,"[{'name': 'ルシノ / rusino', 'url': 'https://www....",2026-07-21T12:47:14.153Z,[YouTube],[YouTube watch history],NaN,NaN,NaN,ルシノ / rusino
...,...,...,...,...,...,...,...,...,...,...,...
42194,YouTube,POWER OF [[NEO]] (BIG SHOT) :: Deltarune Chapt...,https://www.youtube.com/watch?v=mSppviwSUko,"[{'name': 'Geshtro', 'url': 'https://www.youtu...",2025-02-17T00:48:13.926Z,[YouTube],[YouTube watch history],NaN,NaN,NaN,Geshtro
42195,YouTube,Undertale - Mettaton NEO v2.0 (Fan-made),https://www.youtube.com/watch?v=0CteVubVnx8,"[{'name': 'A Huge Pancake', 'url': 'https://ww...",2025-02-17T00:40:56.630Z,[YouTube],[YouTube watch history],NaN,NaN,NaN,A Huge Pancake
42196,YouTube,"Undertale: Power of ""NEO"" (IKARUS Remix)",https://www.youtube.com/watch?v=uI0CxTgpA6Q,"[{'name': 'BlastProcessed', 'url': 'https://ww...",2025-02-17T00:38:41.966Z,[YouTube],[YouTube watch history],NaN,NaN,NaN,BlastProcessed
42198,YouTube,Dançe Do Sonic (Baile Funk) [@fazomadeabangerr],https://www.youtube.com/watch?v=g-BWnNahE1I,"[{'name': 'fazomadeabanger*', 'url': 'https://...",2025-02-17T00:36:29.163Z,[YouTube],[YouTube watch history],NaN,NaN,NaN,fazomadeabanger*
42199,YouTube,𝘿𝙖𝙣ç𝙖 𝘿𝙤 𝙎𝙤𝙣𝙞𝙘 - 𝙛𝙖𝙯𝙤𝙗𝙚𝙖𝙩𝙨 (𝙨𝙡𝙤𝙬𝙚𝙙 𝙩𝙤 𝙥𝙚𝙧𝙛𝙚𝙘𝙩𝙞...,https://www.youtube.com/watch?v=eD_uEg-Kwe0,"[{'name': '𝙀𝙜𝙤𝙞𝙨𝙪𝙩𝙤 | エゴイスト', 'url': 'https://...",2025-02-17T00:35:44.802Z,[YouTube],[YouTube watch history],NaN,NaN,NaN,𝙀𝙜𝙤𝙞𝙨𝙪𝙩𝙤 | エゴイスト

In [13]:
#Converting time format to something human legible
df['time'] = pd.to_datetime(df['time'], errors = 'coerce')
df

,header,title,titleUrl,subtitles,time,products,activityControls,description,details,source,channelName
0,YouTube,Kubbi and Chumpatrol1 / Restoration of the Cairn,https://www.youtube.com/watch?v=cNz8GIDLn2A,"[{'name': 'Chumpatrol1', 'url': 'https://www.y...",2026-07-21 13:04:17.545000+00:00,[YouTube],[YouTube watch history],NaN,NaN,NaN,Chumpatrol1
2,YouTube,Kubbi - Pathfinder (Official Music Video),https://www.youtube.com/watch?v=EwNsnPfnIoU,"[{'name': 'Kubbi', 'url': 'https://www.youtube...",2026-07-21 13:03:54.932000+00:00,[YouTube],[YouTube watch history],NaN,NaN,NaN,Kubbi
3,YouTube,Kubbi / Cascade,https://www.youtube.com/watch?v=B4ZjUoEKiLs,"[{'name': 'Kubbi', 'url': 'https://www.youtube...",2026-07-21 13:03:50.258000+00:00,[YouTube],[YouTube watch history],NaN,NaN,NaN,Kubbi
4,YouTube,Kubbi / Pathfinder,https://www.youtube.com/watch?v=KRm2zCqwd1c,"[{'name': 'Kubbi', 'url': 'https://www.youtube...",2026-07-21 13:03:31.732000+00:00,[YouTube],[YouTube watch history],NaN,NaN,NaN,Kubbi
5,YouTube,"ループザルーム feat. 初音ミク / ""Looping the Rooms"" ft. H...",https://www.youtube.com/watch?v=icBDYkfxpMs,"[{'name': 'ルシノ / rusino', 'url': 'https://www....",2026-07-21 12:47:14.153000+00:00,[YouTube],[YouTube watch history],NaN,NaN,NaN,ルシノ / rusino
...,...,...,...,...,...,...,...,...,...,...,...
42194,YouTube,POWER OF [[NEO]] (BIG SHOT) :: Deltarune Chapt...,https://www.youtube.com/watch?v=mSppviwSUko,"[{'name': 'Geshtro', 'url': 'https://www.youtu...",2025-02-17 00:48:13.926000+00:00,[YouTube],[YouTube watch history],NaN,NaN,NaN,Geshtro
42195,YouTube,Undertale - Mettaton NEO v2.0 (Fan-made),https://www.youtube.com/watch?v=0CteVubVnx8,"[{'name': 'A Huge Pancake', 'url': 'https://ww...",2025-02-17 00:40:56.630000+00:00,[YouTube],[YouTube watch history],NaN,NaN,NaN,A Huge Pancake
42196,YouTube,"Undertale: Power of ""NEO"" (IKARUS Remix)",https://www.youtube.com/watch?v=uI0CxTgpA6Q,"[{'name': 'BlastProcessed', 'url': 'https://ww...",2025-02-17 00:38:41.966000+00:00,[YouTube],[YouTube watch history],NaN,NaN,NaN,BlastProcessed
42198,YouTube,Dançe Do Sonic (Baile Funk) [@fazomadeabangerr],https://www.youtube.com/watch?v=g-BWnNahE1I,"[{'name': 'fazomadeabanger*', 'url': 'https://...",2025-02-17 00:36:29.163000+00:00,[YouTube],[YouTube watch history],NaN,NaN,NaN,fazomadeabanger*
42199,YouTube,𝘿𝙖𝙣ç𝙖 𝘿𝙤 𝙎𝙤𝙣𝙞𝙘 - 𝙛𝙖𝙯𝙤𝙗𝙚𝙖𝙩𝙨 (𝙨𝙡𝙤𝙬𝙚𝙙 𝙩𝙤 𝙥𝙚𝙧𝙛𝙚𝙘𝙩𝙞...,https://www.youtube.com/watch?v=eD_uEg-Kwe0,"[{'name': '𝙀𝙜𝙤𝙞𝙨𝙪𝙩𝙤 | エゴイスト', 'url': 'https://...",2025-02-17 00:35:44.802000+00:00,[YouTube],[YouTube watch history],NaN,NaN,NaN,𝙀𝙜𝙤𝙞𝙨𝙪𝙩𝙤 | エゴイスト

In [14]:
#Dropping unnecessary columns
df = df.drop(columns = ['header', 'subtitles', 'products', 'activityControls', 'description', 'details', 'source'])
df

,title,titleUrl,time,channelName
0,Kubbi and Chumpatrol1 / Restoration of the Cairn,https://www.youtube.com/watch?v=cNz8GIDLn2A,2026-07-21 13:04:17.545000+00:00,Chumpatrol1
2,Kubbi - Pathfinder (Official Music Video),https://www.youtube.com/watch?v=EwNsnPfnIoU,2026-07-21 13:03:54.932000+00:00,Kubbi
3,Kubbi / Cascade,https://www.youtube.com/watch?v=B4ZjUoEKiLs,2026-07-21 13:03:50.258000+00:00,Kubbi
4,Kubbi / Pathfinder,https://www.youtube.com/watch?v=KRm2zCqwd1c,2026-07-21 13:03:31.732000+00:00,Kubbi
5,"ループザルーム feat. 初音ミク / ""Looping the Rooms"" ft. H...",https://www.youtube.com/watch?v=icBDYkfxpMs,2026-07-21 12:47:14.153000+00:00,ルシノ / rusino
...,...,...,...,...
42194,POWER OF [[NEO]] (BIG SHOT) :: Deltarune Chapt...,https://www.youtube.com/watch?v=mSppviwSUko,2025-02-17 00:48:13.926000+00:00,Geshtro
42195,Undertale - Mettaton NEO v2.0 (Fan-made),https://www.youtube.com/watch?v=0CteVubVnx8,2025-02-17 00:40:56.630000+00:00,A Huge Pancake
42196,"Undertale: Power of ""NEO"" (IKARUS Remix)",https://www.youtube.com/watch?v=uI0CxTgpA6Q,2025-02-17 00:38:41.966000+00:00,BlastProcessed
42198,Dançe Do Sonic (Baile Funk) [@fazomadeabangerr],https://www.youtube.com/watch?v=g-BWnNahE1I,2025-02-17 00:36:29.163000+00:00,fazomadeabanger*
42199,𝘿𝙖𝙣ç𝙖 𝘿𝙤 𝙎𝙤𝙣𝙞𝙘 - 𝙛𝙖𝙯𝙤𝙗𝙚𝙖𝙩𝙨 (𝙨𝙡𝙤𝙬𝙚𝙙 𝙩𝙤 𝙥𝙚𝙧𝙛𝙚𝙘𝙩𝙞...,https://www.youtube.com/watch?v=eD_uEg-Kwe0,2025-02-17 00:35:44.802000+00:00,𝙀𝙜𝙤𝙞𝙨𝙪𝙩𝙤 | エゴイスト

In [15]:
#Resetting the index counts
df.reset_index(drop = True)

,title,titleUrl,time,channelName
0,Kubbi and Chumpatrol1 / Restoration of the Cairn,https://www.youtube.com/watch?v=cNz8GIDLn2A,2026-07-21 13:04:17.545000+00:00,Chumpatrol1
1,Kubbi - Pathfinder (Official Music Video),https://www.youtube.com/watch?v=EwNsnPfnIoU,2026-07-21 13:03:54.932000+00:00,Kubbi
2,Kubbi / Cascade,https://www.youtube.com/watch?v=B4ZjUoEKiLs,2026-07-21 13:03:50.258000+00:00,Kubbi
3,Kubbi / Pathfinder,https://www.youtube.com/watch?v=KRm2zCqwd1c,2026-07-21 13:03:31.732000+00:00,Kubbi
4,"ループザルーム feat. 初音ミク / ""Looping the Rooms"" ft. H...",https://www.youtube.com/watch?v=icBDYkfxpMs,2026-07-21 12:47:14.153000+00:00,ルシノ / rusino
...,...,...,...,...
26195,POWER OF [[NEO]] (BIG SHOT) :: Deltarune Chapt...,https://www.youtube.com/watch?v=mSppviwSUko,2025-02-17 00:48:13.926000+00:00,Geshtro
26196,Undertale - Mettaton NEO v2.0 (Fan-made),https://www.youtube.com/watch?v=0CteVubVnx8,2025-02-17 00:40:56.630000+00:00,A Huge Pancake
26197,"Undertale: Power of ""NEO"" (IKARUS Remix)",https://www.youtube.com/watch?v=uI0CxTgpA6Q,2025-02-17 00:38:41.966000+00:00,BlastProcessed
26198,Dançe Do Sonic (Baile Funk) [@fazomadeabangerr],https://www.youtube.com/watch?v=g-BWnNahE1I,2025-02-17 00:36:29.163000+00:00,fazomadeabanger*
26199,𝘿𝙖𝙣ç𝙖 𝘿𝙤 𝙎𝙤𝙣𝙞𝙘 - 𝙛𝙖𝙯𝙤𝙗𝙚𝙖𝙩𝙨 (𝙨𝙡𝙤𝙬𝙚𝙙 𝙩𝙤 𝙥𝙚𝙧𝙛𝙚𝙘𝙩𝙞...,https://www.youtube.com/watch?v=eD_uEg-Kwe0,2025-02-17 00:35:44.802000+00:00,𝙀𝙜𝙤𝙞𝙨𝙪𝙩𝙤 | エゴイスト

In [16]:
#Importing my subscription data to join it with my watch history
df2 = pd.read_csv(r"C:\Users\0106o\OneDrive\Pictures\Documents\Datasets\Youtube Project Files\subscriptions\subscriptions.csv")
df2

,Channel Id,Channel Url,Channel Title
0,UC-3Hil-SglzWOnDMCM5D0LA,http://www.youtube.com/channel/UC-3Hil-SglzWOn...,SimbaThaGod
1,UC-3J5xNrAbTLbU1gN8mMpOA,http://www.youtube.com/channel/UC-3J5xNrAbTLbU...,Nitro Rad
2,UC-6xK8GHYM-oNr4AF5bRDKA,http://www.youtube.com/channel/UC-6xK8GHYM-oNr...,APS Amplifier
3,UC-7nELDbJEPF3muAzSeT74g,http://www.youtube.com/channel/UC-7nELDbJEPF3m...,Disrupt
4,UC-9QiiVaViuqMhLp1XEwdxA,http://www.youtube.com/channel/UC-9QiiVaViuqMh...,Arlo
...,...,...,...
1423,UCzkGDBl3d0XvFCvIOfMkgkw,http://www.youtube.com/channel/UCzkGDBl3d0XvFC...,DJ Zips
1424,UCzkY0h7rwQjAlNW1NIz4H4g,http://www.youtube.com/channel/UCzkY0h7rwQjAlN...,SharaX Official
1425,UCzwcf_Wivsckwp1uQwTu8Xg,http://www.youtube.com/channel/UCzwcf_Wivsckwp...,TotoTriceps
1426,UCzxam5bmSXDrnnIXLvNFOkQ,http://www.youtube.com/channel/UCzxam5bmSXDrnn...,Baron's Castle
1427,UCzycs8MqvIY4nXWwS-v4J9g,http://www.youtube.com/channel/UCzycs8MqvIY4nX...,ONE OK ROCK

In [17]:
#Creating a true or false column to check if the watched videos are from one of my subscriptions
df['subscribed'] = df['channelName'].isin(df2['Channel Title'])
df

,title,titleUrl,time,channelName,subscribed
0,Kubbi and Chumpatrol1 / Restoration of the Cairn,https://www.youtube.com/watch?v=cNz8GIDLn2A,2026-07-21 13:04:17.545000+00:00,Chumpatrol1,False
2,Kubbi - Pathfinder (Official Music Video),https://www.youtube.com/watch?v=EwNsnPfnIoU,2026-07-21 13:03:54.932000+00:00,Kubbi,True
3,Kubbi / Cascade,https://www.youtube.com/watch?v=B4ZjUoEKiLs,2026-07-21 13:03:50.258000+00:00,Kubbi,True
4,Kubbi / Pathfinder,https://www.youtube.com/watch?v=KRm2zCqwd1c,2026-07-21 13:03:31.732000+00:00,Kubbi,True
5,"ループザルーム feat. 初音ミク / ""Looping the Rooms"" ft. H...",https://www.youtube.com/watch?v=icBDYkfxpMs,2026-07-21 12:47:14.153000+00:00,ルシノ / rusino,True
...,...,...,...,...,...
42194,POWER OF [[NEO]] (BIG SHOT) :: Deltarune Chapt...,https://www.youtube.com/watch?v=mSppviwSUko,2025-02-17 00:48:13.926000+00:00,Geshtro,False
42195,Undertale - Mettaton NEO v2.0 (Fan-made),https://www.youtube.com/watch?v=0CteVubVnx8,2025-02-17 00:40:56.630000+00:00,A Huge Pancake,False
42196,"Undertale: Power of ""NEO"" (IKARUS Remix)",https://www.youtube.com/watch?v=uI0CxTgpA6Q,2025-02-17 00:38:41.966000+00:00,BlastProcessed,False
42198,Dançe Do Sonic (Baile Funk) [@fazomadeabangerr],https://www.youtube.com/watch?v=g-BWnNahE1I,2025-02-17 00:36:29.163000+00:00,fazomadeabanger*,True
42199,𝘿𝙖𝙣ç𝙖 𝘿𝙤 𝙎𝙤𝙣𝙞𝙘 - 𝙛𝙖𝙯𝙤𝙗𝙚𝙖𝙩𝙨 (𝙨𝙡𝙤𝙬𝙚𝙙 𝙩𝙤 𝙥𝙚𝙧𝙛𝙚𝙘𝙩𝙞...,https://www.youtube.com/watch?v=eD_uEg-Kwe0,2025-02-17 00:35:44.802000+00:00,𝙀𝙜𝙤𝙞𝙨𝙪𝙩𝙤 | エゴイスト,False

In [18]:
#Checking if the ratio of subscribed content to unsubscribed content makes sense
df['subscribed'].value_counts()

subscribed
False    20483
True      5717
Name: count, dtype: int64

In [19]:
df.to_csv(r"C:\Users\0106o\OneDrive\Pictures\Documents\Datasets\Youtube Project Files\youtube_clean.csv", index=False)